### PR TITLE
Dockerfile for 3.0.0 based on  node:8.2.1-alpine (alpine:3.6)

### PR DESCRIPTION
**Pull request by Kitanotori**
https://github.com/deepstreamIO/deepstream.io/issues/753

### CODE REVIEW

**Comment by yasserf** [comment]
👍  Thank you!

**Comment by yasserf** [comment]
Before I can merge, would you be okay with signing our CLA?

https://deepstream.typeform.com/to/PwwNd5

**Comment by Kitanotori** [comment]
I signed the CLA a while ago.

**Comment by yasserf** [comment]
Brilliant, thank you!

**Pull request merged**
